version: '3'

services:
  postgresql:
    image: postgres
    container_name: shop
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=shop
      - POSTGRES_PASSWORD=shop
      - POSTGRES_DATABASE=shop
    command: postgres
    restart: always


